version: 1
policies:
  - id: setup-miniconda-policy
    repo: setup-miniconda
    teams:
      - setup-miniconda
      - steering
access_control:
  - resource: cirun-openstack-cpu-small
    policies:
      - setup-miniconda-policy
